language: java
jdk: oraclejdk8

env:
  - VERSION=0.1.0

cache:
  directories:
    - $HOME/.m2

script:
  - (cd src/main/resources/META-INF/resources && yarn install)
  - if [ $TRAVIS_BRANCH == 'master' ] && [ -z "$TRAVIS_TAG" ] ; then export VERSION="$VERSION-SNAPSHOT" ; fi
  - if [ ! -z "$TRAVIS_TAG" ] ; then export VERSION=$TRAVIS_TAG ; fi
  - if [ $TRAVIS_BRANCH == 'master' ] ; then mvn --quiet versions:set -DnewVersion=$VERSION ; fi
  - mvn --quiet clean verify

deploy:
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn --quiet deploy"
    on:
      branch: master
