language: java
jdk: oraclejdk8

env:
  - VERSION=1.0.0

cache:
  directories:
    - $HOME/.m2

script:
  - cd src/main/resources/META-INF/resources
  - yarn install
  - cd -
  - if [ $TRAVIS_BRANCH == 'develop' ] ; then export VERSION="$VERSION-SNAPSHOT" ; fi
  - if [ $TRAVIS_BRANCH == 'master' ] || [ $TRAVIS_BRANCH == 'develop' ] ; then mvn --quiet versions:set -DnewVersion=$VERSION ; fi
  - mvn --quiet clean verify

deploy:
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn --quiet deploy"
    on:
      branch: master
      tags: false
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn --quiet deploy"
    on:
      branch: master
      tags: true
